### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Zuko** [nhat-nguyen/steam-discovery#1]
Could you update it? 

```
Submitting login form...
Submitted login form...
Starting the queue at http://store.steampowered.com/app/107410/Arma_3/?snr=1_239_4__122
```

and stops.

**Comment by gmmanonymus111** [comment]
mine couldn't even log in, at least with steam authenticator....

**Comment by nhat-nguyen** [comment]
I first wrote this 2 years ago, so there are certainly changes that have been made to Steam. That's why this no longer works...

**Comment by gmmanonymus111** [comment]
i figured that out, and made it compatible with 2fa, my only pprolem is that steam changes the language even if i add `?l=en` after every url. Is there a way to solve this without using a proxy?

**Comment by nhat-nguyen** [comment]
Did you try `?l=english`? It seems to work fine. If you are able to make the script compatible with 2FA, just make a PR, I'll be happy to merge it! :D

**Comment by Zuko** [comment]
even if you log in, script just not working further

**Comment by gmmanonymus111** [comment]
`?l=en` in the same as `?l=english`, but it always keep changing back to hungarian, only at the start of the queue... at least the login is fixed now ^^

`Successfully logged in...`
`Starting the queue at http://store.steampowered.com/explore/next/`
`Currently at: Felfedez├ęsi v├ír├│list├íd`
`Wait timeout of 60000ms expired, exiting.`

it might need a little change, hopefully i get it working again somehow

**Comment by Zuko** [comment]
you should look at "new" agecheck

ugly:
```
        var byPassAgeCheck = function(arr) {
            var oldAgeCheck = function(arr) {
                console.log('Bypassing old age-check...');
                var currentUrl = casper.getCurrentUrl();
                casper.evaluate(function() {
                    document.querySelector('select[name=ageYear]').value = 1990;
                    DoAgeGateSubmit();
                    console.log('Submitted age...');
                    return false;
                });
                if (arr !== undefined) arr.push(arr.length);
                casper.waitForUrlChange(currentUrl);
            };
            var newAgeCheck = function(arr) {
                console.log('Bypassing new age-check...');
                var currentUrl = casper.getCurrentUrl();
                casper.evaluate(function() {
                    HideAgeGate(String(window.location).match(/\/app\/(\d+)\/agecheck$/i)[1]);
                    console.log('Submitted age...');
                    return false;
                });
                if (arr !== undefined) arr.push(arr.length);
                casper.waitForUrlChange(currentUrl);
            };
            var currentUrl = casper.getCurrentUrl();
            if (currentUrl.indexOf('agecheck') > -1) { // has age check
                if (currentUrl.match(/\/agecheck\/app\//)) {
                    oldAgeCheck(arr);
                } else {
                    newAgeCheck(arr);
                }
            }
        };
```

**Comment by gmmanonymus111** [comment]
the old age checker is fine, and it seems to be working for me after a restart... **until the next queue start**
`Successfully logged in...`
`Getting new queue...`
`Bypassing age-check...`
`Currently at: Sp├│rolj meg 75%-ot a(z) Saints Row: The Third ├ír├íb├│l a Steamen`
`Currently at: Sp├│rolj meg 50%-ot a(z) Duke Nukem 3D: 20th Anniversary World Tour ├ír├íb├│l a Steamen`
`Currently at: Sp├│rolj meg 20%-ot a(z) Black Desert Online ├ír├íb├│l a Steamen`
`Currently at: Sp├│rolj meg 90%-ot a(z) Serious Sam HD: The First Encounter ├ír├íb├│l a Steamen`
`Currently at: Wolfenstein II: The New Colossus el┼Ĺv├ís├írl├ísa a Steamen`
`Currently at: Sp├│rolj meg 50%-ot a(z) Call of Duty┬«: Black Ops ├ír├íb├│l a Steamen`
`Currently at: Gotham City Impostors Free to Play a Steamen`
`Currently at: Sp├│rolj meg 60%-ot a(z) Black Mesa ├ír├íb├│l a Steamen`
`Currently at: America's Army: Proving Grounds a Steamen`
`Currently at: Sp├│rolj meg 67%-ot a(z) Keep Talking and Nobody Explodes ├ír├íb├│l a Steamen`
`Currently at: Sp├│rolj meg 50%-ot a(z) HELLDIVERSÔäó ├ír├íb├│l a Steamen`
`Currently at: Sp├│rolj meg 25%-ot a(z) Shadow Tactics: Blades of the Shogun ├ír├íb├│l a Steamen`
`Bypassing age-check...`
`Currently at: Felfedez├ęsi v├ír├│list├íd`

Something gone wrong at the start of the queue

**Comment by gmmanonymus111** [comment]
Ok, it seems to be stable
As for the language, you need to set it in your account's settings to remain engish...

**Comment by nhat-nguyen** [comment]
What changes did you make to make it work?

**Comment by gmmanonymus111** [comment]
Well, only the 2fa support, and  put `?l=en` after some links (which is pointless after you set your language) and fixed some of your typos
Trying to make a pull request, but github doesn't want to be installed on my machine (some kind of loop)

**Comment by Zuko** [comment]
just post it here

**Comment by gmmanonymus111** [comment]
Pull request created!

**Comment by Zuko** [comment]
great, but I have a "little" request: 
to grab all cards each day you need to finish three queues , can you add "loop" for that?

**Comment by nhat-nguyen** [comment]
@Zuko I can do that when I have time 👍

**Comment by Zuko** [comment]
thanks

**Comment by gmmanonymus111** [comment]
Created another pull request ^^
